swagger: '2.0'
info:
  title: swimset-api
  description: This API generates a training set
  version: '1.02'
schemes:
  - https
basePath: /swimset-v102
produces:
  - application/json  
paths:
  /generateTraining:
    post:
      operationId: generateTraining
      parameters:
        - in: path
          name: distance
          type: string
          required: true
          description: training distance
      x-google-backend:
        address: https://australia-southeast1-swimset.cloudfunctions.net/swimset-v102
      security:
        - api_key_header: []
      consumes:
        - application/json        
      produces:
        - application/json        
      responses:
        '200':
          description: OK
securityDefinitions:
  api_key_header:
    type: apiKey
    name: x-api-key
    in: header
  api_key_query_1:
    type: apiKey
    name: api_key
    in: query
  api_key_query_2:
    type: apiKey
    name: apikey
    in: query